- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.zshenv:
      path: zsh/.zshenv
      force: true
    ~/.config/zsh: zsh
    ~/.config/vim: vim
    ~/.config/nvim: vim
    ~/.config/bash: bash
    ~/.tmux.conf: tmux/.tmux.conf
    ~/.local/share/tmux: tpm
    ~/.config/utils: utils
    ~/.gitconfig: configs/.gitconfig
    ~/.config/curl/.curlrc: configs/.curlrc
    ~/.Brewfile:
      if: '[ `uname` = Darwin ]'
      path: installs/.Brewfile
    ~/.macos:
      if: '[ `uname` = Darwin ]'
      path: configs/.macos
    ~/.finicky.js:
      if: '[ `uname` = Darwin ]'
      path: configs/.finicky.js
- shell:
  - git submodule sync --recursive
