- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '${XDG_CONFIG_HOME}']

- shell:
  - description: Set XDG environmental variables
    command: source ./zsh/.zshenv
  - description: Check that $XDG_CONFIG_HOME is set
    command: >
      if [ -z ${XDG_CONFIG_HOME+x} ]; then; \
        echo "XDG_CONFIG_HOME is not yet set. Will use ~/.config"; \
        XDG_CONFIG_HOME="${HOME}/.config"; \
      fi
    stdin: false
    stdout: true
    stderr: true
    quiet: true
  - description: Check that $XDG_DATA_HOME is set
    command: >
      if [ -z ${XDG_DATA_HOME+x} ]; then; \
        echo "XDG_DATA_HOME is not yet set. Will use ~/.local/share"; \
        XDG_DATA_HOME="${HOME}/.local/share"; \
      fi
    stdin: false
    stdout: true
    stderr: true
    quiet: true


- link:
    ~/.zshenv:
      path: zsh/.zshenv
      force: true
    ${XDG_CONFIG_HOME}/zsh: zsh
    ${XDG_CONFIG_HOME}/vim: vim
    ${XDG_CONFIG_HOME}/nvim: vim
    ${XDG_CONFIG_HOME}/bash: bash
    ${XDG_DATA_HOME}/tmux/plugins/tpm: tpm
    ${XDG_CONFIG_HOME}/tmux/tmux.conf: tmux/tmux.conf
    ${XDG_CONFIG_HOME}/utils: utils
    ~/.gitconfig: configs/.gitconfig
    ${XDG_CONFIG_HOME}/.gitignore_global: configs/.gitignore_global
    # ${XDG_CONFIG_HOME}/curl/.curlrc: configs/.curlrc
    ~/.Brewfile:
      if: '[ `uname` = Darwin ]'
      path: installs/.Brewfile
    ~/.macos:
      if: '[ `uname` = Darwin ]'
      path: configs/.macos
    ~/.finicky.js:
      if: '[ `uname` = Darwin ]'
      path: configs/.finicky.js

- create:
    - ~/Downloads
    - ~/Documents
    - ~/Applications
