# This file specifies folders for the MacOS launchpad, and which apps should be nested where.
# It's useful for setting up fresh systems quickly, after installing all required dependencies.
# Requires lporg (brew install blacktop/tap/lporg), run `lporg load [file]` to restore layout.

apps:
  pages:
  - number: 1
    items:
    - folder: Dev
      pages:
      - number: 1
        items:
        - Xcode
        - Android Studio
        - Docker
        - Postman
        - Boop
        - Sourcetree
        - UTM
        - Visual Studio
    - folder: Work Coms
      pages:
      - number: 1
        items:
        - zoom.us
        - Slack
        - Google Chrome
        - Calendar
        - Mail
        - Microsoft Teams
    - folder: Security
      pages:
      - number: 1
        items:
        - Wireshark
        - OWASP ZAP
        - Burp Suite Community Edition
    - folder: Media
      pages:
      - number: 1
        items:
        - GIMP-2.10
        - VLC
        - Transmission
        - Audacity
        - OBS
        - Spotify
        - Inkscape
        - Shotcut
        - calibre
    - folder: Personal
      pages:
      - number: 1
        items:
        - Standard Notes
        - 1Password
        - VeraCrypt
        - Tresorit
        - Proton Mail Bridge
        - ProtonVPN
        - GPG Keychain
        - Signal
        - Ledger Live
        - etesync-dav
    - folder: Mac Mods
      pages:
      - number: 1
        items:
        - Raycast
        - Scroll Reverser
        - Hidden Bar
        - AltTab
        - Finicky
        - Stats
        - Little Snitch
        - Espanso
        - CopyQ
        - PopClip
        - OpenInTerminal
        - AnyBar
        - Marta
        - Mjolnir
        - LinearMouse
        - Übersicht
        - Shottr
        - OnyX
    - folder: Other
      pages:
      - number: 1
        items:
        - Shortcuts
        - QuickTime Player
        - TextEdit
        - Grapher
        - Time Machine
        - Font Book
        - Chess
        - Stickies
        - Image Capture
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Terminal
        - Activity Monitor
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Digital Color Meter
        - ColorSync Utility
        - Screenshot
        - Bluetooth File Exchange
        - Audio MIDI Setup
        - Developer
        - Jabra Firmware Update
        - Jabra Direct
        - System Preferences
        - Calculator
        - Dictionary
        - CotEditor
        - VMware Fusion Tech Preview
        - TestFlight
        - Simulator
      - number: 2
        items:
        - Orion
        - Keka
        - Mountain Duck
        - DaisyDisk
    - folder: Apple Crap
      pages:
      - number: 1
        items:
        - Contacts
        - Reminders
        - Notes
        - FaceTime
        - Messages
        - Maps
        - Find My
        - Photo Booth
        - Photos
        - Preview
        - Music
        - Podcasts
        - TV
        - Voice Memos
        - Numbers
        - Keynote
        - Pages
        - News
        - Stocks
        - Books
        - Siri
        - App Store
        - Mission Control
        - Safari
        - Home
    - folder: Corporate Spyware
      pages:
      - number: 1
        items:
        - Netskope Client
        - Self Service
        - Solarwinds Discovery Agent
        - Sophos Endpoint
        - Sophos Endpoint Self Help
        - Sophos Network Extension
        - Sophos Scan
        - Remove Sophos Endpoint
        - Remove Netskope Client
    - folder: Voldermort
      pages:
      - number: 1
        items:
        - Google Sheets
        - Google Slides
        - Google Docs
        - Google Drive
    - Firefox
    - Chromium
    - Visual Studio Code
    - iTerm
# widgets:
#   pages: []
# dock_items:
# - ============
# desktop: {}
